# Generated by Django 3.1.3 on 2020-11-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
       
    ]
