# Generated by Django 3.1.3 on 2020-11-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_event_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='accept_information_rule',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='foreign_flag',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='registration_in_city',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='social_security',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
