# Generated by Django 3.1.3 on 2020-12-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201214_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='id_number',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
