# Generated by Django 3.1.3 on 2020-11-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201117_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='foreign_flag',
            field=models.BooleanField(default=False),
        ),
    ]
