# Generated by Django 3.1.3 on 2020-12-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201221_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speaker',
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.speaker')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ManyToManyField(through='account.EventSpeaker', to='account.Speaker'),
        ),
    ]
