# Generated by Django 3.1.3 on 2020-12-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201222_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeaker',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
