# Generated by Django 3.1.3 on 2020-12-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_password_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='person_type',
        ),
        migrations.AddField(
            model_name='speaker',
            name='juridcal_person',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_link',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
