# Generated by Django 3.1.3 on 2020-12-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20201230_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeaker',
            name='role',
            field=models.CharField(default=1, max_length=191),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='tier',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
