# Generated by Django 3.1.3 on 2020-12-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_speaker_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspeaker',
            name='role',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
