# Generated by Django 3.1.3 on 2021-01-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20201231_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='displacement',
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='displacement',
            field=models.CharField(default='', max_length=191),
            preserve_default=False,
        ),
    ]
