# Generated by Django 3.1.3 on 2021-01-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210106_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('birthday', models.DateField()),
                ('relationship', models.CharField(max_length=191)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.speaker')),
            ],
        ),
    ]
