# Generated by Django 3.1.3 on 2021-01-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_speakerperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerperson',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.speaker'),
        ),
    ]
