# Generated by Django 3.1.3 on 2021-03-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_eventproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='web',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
