version: "3.3"
   
services:
  db:
    image: mysql:5.7
    ports:
      - "3302:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=knight12
      - MYSQL_DATABASE=knight
      - MYSQL_PASSWORD=knight12
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - MYSQL_HOST=db
    depends_on:
      - db
